alias ".."="cd .."
alias b="bat --style=plain"
alias bcli="bitcoin-cli"
alias bp="bat --style=plain --paging=always"
alias c="clear"
alias cdd="cd ~/dotfiles"
alias date='date +%d-%m-%y'
alias dot="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias gaa="git add -u"
alias gap="git add -p"
alias gbr="git branch --sort=-committerdate"
alias gcb="git checkout -b"
alias gcm="git commit --verbose"
alias gdf="git diff --name-only master | uniq | xargs $EDITOR"
alias ghprc="gh pr checkout"
alias gpa="for remote in `git remote`; do git push $remote; done"
alias gpf="git push --force-with-lease"
alias gpom="git pull origin master"
alias gpum="git pull upstream master"
alias grep='rg -i'
alias gs="git status"
alias h="hx"
alias j="just --unstable"
alias ja="just --unstable atlantis"
alias jc="just --unstable --choose"
alias jl="just --unstable --list"
alias la="ls -laGh"
alias ll="ls -lGh"
alias ls="ls -G"
alias lv="nvim -c \"normal '0\" -c bd1"
# alias man="colorful_man"
alias o="open ."
alias p="python -q"
alias qr="qrencode -t ansiutf8"
alias rap="return_and_pop.sh"
alias rg="rg -i"
alias s="source $HOME/.zshrc"
alias tma="tmux attach-session"
alias tml="tmux list-sessions"
alias tmn="tmux new -s"
alias tree="erd -H"
alias unixt="date '+%s'"
alias unixt='\date +%s'
alias utc='\date -u +%H:%M:%S'
alias v="nvim"
alias vims="cd ~/.config/nvim && nvim init.lua"
